import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  frameworkSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "framework/feature-catalog",
        "framework/load-profiles",
        "framework/test-types",
        "framework/workflow",
      ],
    },
    {
      type: "category",
      label: "Helpers",
      items: [
        "framework/helpers/quick-request",
        "framework/helpers/redis-data",
        "framework/helpers/generators",
        "framework/helpers/groups-custom-metrics",
      ],
    },
    {
      type: "category",
      label: "Patterns",
      items: ["framework/patterns/patterns-guide", "framework/patterns/mocks-chaos"],
    },
    {
      type: "category",
      label: "Metrics & SLOs",
      items: ["framework/metrics/metrics-engine", "framework/metrics/sla-slo"],
    },
    {
      type: "category",
      label: "Reporting",
      items: ["framework/reporting/reporting", "framework/reporting/benchmarking"],
    },
    {
      type: "category",
      label: "Observability",
      items: [
        "framework/observability/grafana",
        "framework/observability/docker",
        "framework/observability/distributed-testing",
      ],
    },
    {
      type: "category",
      label: "Security",
      items: [
        "framework/security/security",
        "framework/security/security-audit-examples",
        "framework/security/security-permissions",
        "framework/security/compliance-checklist",
      ],
    },
    {
      type: "category",
      label: "CI/CD",
      items: ["framework/ci-cd/ci-cd-integration", "framework/ci-cd/batch-execution"],
    },
    {
      type: "category",
      label: "AI & Integrations",
      items: ["framework/ai/agents", "framework/ai/ai-config", "framework/ai/mcp-server"],
    },
    {
      type: "category",
      label: "Advanced",
      items: [
        "framework/advanced/custom-binary",
        "framework/advanced/extension-points",
        "framework/advanced/client-management",
        "framework/advanced/client-repository",
      ],
    },
    {
      type: "category",
      label: "Development",
      items: [
        "framework/development/code-quality",
        "framework/development/contributing",
        "framework/development/roadmap",
      ],
    },
  ],

  clientsSidebar: [
    {
      type: "autogenerated",
      dirName: "clients",
    },
  ],

  k6ReportSidebar: [
    "k6-report/index",
    {
      type: "category",
      label: "Usage",
      collapsed: false,
      items: ["k6-report/cli-reference", "k6-report/api-reference"],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        "k6-report/report-sections",
        "k6-report/analysis-engine",
        "k6-report/export-formats",
        "k6-report/capacity-trend",
        "k6-report/storage",
      ],
    },
  ],
};

export default sidebars;
