// DO NOT EDIT — generated by build-binary.sh
// This file is regenerated on every build and is not checked into git.
package main

import (
	"fmt"
	"os"
	"strings"

	k6embed "k6-embedded"

	"go.k6.io/k6/cmd"
)

const clientID = "{{CLIENT_ID}}"

func main() {
	args := os.Args[1:]

	// Intercept "list-scripts" before delegating to k6.
	if len(args) > 0 && args[0] == "list-scripts" {
		scripts := k6embed.ListScripts()
		if len(scripts) == 0 {
			fmt.Fprintln(os.Stderr, "No embedded scripts found.")
			os.Exit(1)
		}
		fmt.Printf("Embedded scripts in k6-%s:\n", clientID)
		for _, s := range scripts {
			fmt.Printf("  embedded://%s\n", s)
		}
		os.Exit(0)
	}

	// Rewrite "embedded://<path>" argument to a real temp file path.
	// k6 run embedded://api/01-auth-bearer  →  k6 run /tmp/k6-embedded-run/dummy/api/01-auth-bearer.js
	// Data files are extracted alongside so open("../../data/file") resolves correctly.
	rewritten := make([]string, len(args))
	hasEmbedded := false
	for i, arg := range args {
		if strings.HasPrefix(arg, "embedded://") {
			relPath := strings.TrimPrefix(arg, "embedded://")
			tmpPath, err := k6embed.WriteScript(relPath)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n\n", err)
				fmt.Fprintf(os.Stderr, "Available scripts (run 'k6-%s list-scripts'):\n", clientID)
				for _, s := range k6embed.ListScripts() {
					fmt.Fprintf(os.Stderr, "  embedded://%s\n", s)
				}
				os.Exit(1)
			}
			rewritten[i] = tmpPath
			hasEmbedded = true
		} else {
			rewritten[i] = arg
		}
	}

	// Cleanup temp directory on exit.
	if hasEmbedded {
		defer k6embed.CleanupTempFiles()
	}

	// Delegate to k6's own CLI with rewritten args.
	os.Args = append([]string{os.Args[0]}, rewritten...)
	cmd.Execute()
}
